import{AllMangaSource}from'./AllManga.js';
import{MangaPumaSource}from'./MangaPuma.js';
import{RavenScansSource}from'./RavenScans.js';
import{LocalSource}from'./LocalSource.js';
export{AllMangaSource,MangaPumaSource,RavenScansSource,LocalSource};
export const BUILT_INS=[AllMangaSource,MangaPumaSource,RavenScansSource,LocalSource];
export function getSource(id){return BUILT_INS.find(s=>s.id===id)||null;}
export function getAllSources(custom=[]){return[...BUILT_INS,...custom.filter(s=>s.enabled!==false).map(s=>{const b=s.url?.replace(/\/$/,'');const PX='https://corsproxy.io/?';const H={'User-Agent':'Mozilla/5.0','Referer':b};async function gD(url){const r=await fetch(PX+encodeURIComponent(url),{headers:H});if(!r.ok)throw new Error(`HTTP ${r.status}`);return new DOMParser().parseFromString(await r.text(),'text/html');}const abs=url=>{if(!url)return'';if(url.startsWith('http'))return url;if(url.startsWith('//'))return'https:'+url;if(url.startsWith('/'))return new URL(b).origin+url;return url;};const iS=el=>el?.getAttribute('data-src')||el?.getAttribute('src')||'';return{id:s.id,name:s.name,lang:s.lang||'en',baseUrl:b,is18Plus:s.is18Plus||false,isBuiltIn:false,supportsSearch:true,supportsBrowse:false,async search(q){const doc=await gD(`${b}${s.searchPath||'/?s='}${encodeURIComponent(q)}`);return Array.from(doc.querySelectorAll('a')).filter(a=>a.querySelector('img')&&a.href).slice(0,24).map(a=>{const im=a.querySelector('img');const t=im?.alt||a.textContent.trim();if(!t||t.length<2)return null;return{id:abs(a.href),title:t,cover:abs(iS(im)),sourceId:s.id,sourceName:s.name,url:abs(a.href)};}).filter(Boolean);},async browse(){return[];},async getMangaDetails(id){const url=id.startsWith('http')?id:b+id;const doc=await gD(url);const title=doc.querySelector('h1,.manga-title')?.textContent?.trim()||doc.title;const cEl=doc.querySelector('[class*="cover"] img,[class*="poster"] img');const chapters=Array.from(doc.querySelectorAll('[class*="chapter"] a')).map((a,i)=>{const t=a.textContent.trim();return{id:abs(a.href),title:t,number:t.match(/(\d+)/)?.[1]||'0',date:'',index:i,sourceId:s.id,mangaId:id};});return{id,title,cover:abs(iS(cEl)),description:'',genres:[],status:'',sourceId:s.id,sourceName:s.name,url,chapters};},async getPageList(mId,chId){const url=chId.startsWith('http')?chId:b+chId;const doc=await gD(url);const sels=['#readerarea img','.reading-content img','.chapter-content img'];let imgs=[];for(const sel of sels){imgs=doc.querySelectorAll(sel);if(imgs.length)break;}return Array.from(imgs).map((el,i)=>({index:i,url:abs(iS(el))})).filter(p=>p.url&&/\.(jpg|jpeg|png|webp)/i.test(p.url));},};})];
}
